# Generated by Django 2.1.4 on 2018-12-20 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_custkey', models.IntegerField(db_column='C_CUSTKEY', primary_key=True, serialize=False)),
                ('c_name', models.CharField(blank=True, db_column='C_NAME', max_length=25, null=True)),
                ('c_address', models.CharField(blank=True, db_column='C_ADDRESS', max_length=40, null=True)),
                ('c_phone', models.CharField(blank=True, db_column='C_PHONE', max_length=15, null=True)),
                ('c_acctbal', models.FloatField(blank=True, db_column='C_ACCTBAL', null=True)),
                ('c_mktsegment', models.CharField(blank=True, db_column='C_MKTSEGMENT', max_length=10, null=True)),
                ('c_comment', models.CharField(blank=True, db_column='C_COMMENT', max_length=17, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lineitem',
            fields=[
                ('l_orderkey', models.IntegerField(db_column='L_ORDERKEY', primary_key=True, serialize=False)),
                ('l_linenumber', models.IntegerField(db_column='L_LINENUMBER')),
                ('l_quantity', models.FloatField(blank=True, db_column='L_QUANTITY', null=True)),
                ('l_extendedprice', models.FloatField(blank=True, db_column='L_EXTENDEDPRICE', null=True)),
                ('l_discount', models.FloatField(blank=True, db_column='L_DISCOUNT', null=True)),
                ('l_tax', models.FloatField(blank=True, db_column='L_TAX', null=True)),
                ('l_returnflag', models.CharField(blank=True, db_column='L_RETURNFLAG', max_length=1, null=True)),
                ('l_linestatus', models.CharField(blank=True, db_column='L_LINESTATUS', max_length=1, null=True)),
                ('l_shipdate', models.DateField(blank=True, db_column='L_SHIPDATE', null=True)),
                ('l_commitdate', models.DateField(blank=True, db_column='L_COMMITDATE', null=True)),
                ('l_receiptdate', models.DateField(blank=True, db_column='L_RECEIPTDATE', null=True)),
                ('l_shipinstruct', models.CharField(blank=True, db_column='L_SHIPINSTRUCT', max_length=25, null=True)),
                ('l_shipmode', models.CharField(blank=True, db_column='L_SHIPMODE', max_length=10, null=True)),
                ('l_comment', models.CharField(blank=True, db_column='L_COMMENT', max_length=44, null=True)),
            ],
            options={
                'db_table': 'lineitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('n_nationkey', models.IntegerField(db_column='N_NATIONKEY', primary_key=True, serialize=False)),
                ('n_name', models.CharField(blank=True, db_column='N_NAME', max_length=25, null=True)),
                ('n_comment', models.CharField(blank=True, db_column='N_COMMENT', max_length=152, null=True)),
            ],
            options={
                'db_table': 'nation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('o_orderkey', models.IntegerField(db_column='O_ORDERKEY', primary_key=True, serialize=False)),
                ('o_orderstatus', models.CharField(blank=True, db_column='O_ORDERSTATUS', max_length=1, null=True)),
                ('o_totalprice', models.FloatField(blank=True, db_column='O_TOTALPRICE', null=True)),
                ('o_orderdate', models.DateField(blank=True, db_column='O_ORDERDATE', null=True)),
                ('o_orderpriority', models.CharField(blank=True, db_column='O_ORDERPRIORITY', max_length=15, null=True)),
                ('o_clerk', models.CharField(blank=True, db_column='O_CLERK', max_length=15, null=True)),
                ('o_shippriority', models.IntegerField(blank=True, db_column='O_SHIPPRIORITY', null=True)),
                ('o_comment', models.CharField(blank=True, db_column='O_COMMENT', max_length=79, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('p_partkey', models.IntegerField(db_column='P_PARTKEY', primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, db_column='P_NAME', max_length=55, null=True)),
                ('p_emfgr', models.CharField(blank=True, db_column='P_EMFGR', max_length=25, null=True)),
                ('p_brand', models.CharField(blank=True, db_column='P_BRAND', max_length=10, null=True)),
                ('p_type', models.CharField(blank=True, db_column='P_TYPE', max_length=25, null=True)),
                ('p_size', models.IntegerField(blank=True, db_column='P_SIZE', null=True)),
                ('p_container', models.CharField(blank=True, db_column='P_CONTAINER', max_length=10, null=True)),
                ('p_retailprice', models.FloatField(blank=True, db_column='P_RETAILPRICE', null=True)),
                ('p_comment', models.CharField(blank=True, db_column='P_COMMENT', max_length=23, null=True)),
            ],
            options={
                'db_table': 'part',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('r_regionkey', models.IntegerField(db_column='R_REGIONKEY', primary_key=True, serialize=False)),
                ('r_name', models.CharField(blank=True, db_column='R_NAME', max_length=25, null=True)),
                ('r_comment', models.CharField(blank=True, db_column='R_COMMENT', max_length=152, null=True)),
                ('ps_supplycost', models.FloatField(blank=True, db_column='PS_SUPPLYCOST', null=True)),
                ('ps_comment', models.CharField(blank=True, db_column='PS_COMMENT', max_length=199, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('s_suppkey', models.IntegerField(db_column='S_SUPPKEY', primary_key=True, serialize=False)),
                ('s_name', models.CharField(blank=True, db_column='S_NAME', max_length=25, null=True)),
                ('s_address', models.CharField(blank=True, db_column='S_ADDRESS', max_length=40, null=True)),
                ('s_phone', models.CharField(blank=True, db_column='S_PHONE', max_length=15, null=True)),
                ('s_acctbal', models.FloatField(blank=True, db_column='S_ACCTBAL', null=True)),
                ('s_comment', models.CharField(blank=True, db_column='S_COMMENT', max_length=101, null=True)),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partsupp',
            fields=[
                ('ps_partkey', models.ForeignKey(db_column='PS_PARTKEY', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='l_partkey_ps_partkey', serialize=False, to='DBHW.Part')),
                ('ps_availqty', models.IntegerField(blank=True, db_column='PS_AVAILQTY', null=True)),
                ('ps_supplycost', models.FloatField(blank=True, db_column='PS_SUPPLYCOST', null=True)),
                ('ps_comment', models.CharField(blank=True, db_column='PS_COMMENT', max_length=199, null=True)),
            ],
            options={
                'db_table': 'partsupp',
                'managed': False,
            },
        ),
    ]
